// <auto-generated />
using System;
using AssetValueAnalyzer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetValueAnalyzer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AssetValueAnalyzerDbContext))]
    [Migration("20260810195548_AddExchangeRateBackfillCheckpoint")]
    partial class AddExchangeRateBackfillCheckpoint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetValueAnalyzer.Domain.ExchangeRates.ExchangeRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BaseCurrencyCode")
                        .HasColumnType("int");

                    b.Property<decimal>("CashChangeRate")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<decimal>("CashExchangeRate")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<decimal>("CentralBankChangeRate")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<decimal>("CentralBankExchangeRate")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<decimal>("ChangeRate")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<decimal>("CrossRate")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)");

                    b.Property<decimal>("ExchangeRateValue")
                        .HasPrecision(19, 8)
                        .HasColumnType("decimal(19,8)")
                        .HasColumnName("ExchangeRate");

                    b.Property<int>("ForeignCurrencyCode")
                        .HasColumnType("int");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("RetrievedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateTime>("SourceUpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrencyCode", "ForeignCurrencyCode", "RateDate")
                        .IsUnique()
                        .HasDatabaseName("UX_ExchangeRates_CurrencyPair_RateDate");

                    b.ToTable("ExchangeRates", (string)null);
                });

            modelBuilder.Entity("AssetValueAnalyzer.Infrastructure.Persistence.ExchangeRates.ExchangeRateBackfillCheckpoint", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasPrecision(0)
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateOnly>("CompletedThroughDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("ExchangeRateBackfillCheckpoints", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExchangeRateBackfillCheckpoints_SingletonId", "[Id] = 1");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
